import IProduct from '../src/components/intefaces/IProduct'
 const PRODUCT: IProduct[] = [
  {
    "id": 1,
    "title": "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
    "price": 109.95,
    "description": "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
    "category": "accessories and jewelery",
    "image": "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    "rating": { "rate": 3.9, "count": 120 },
    "color": "blue",
    "release": 2021,
    "countInStock": 32
  },
  {
    "id": 2,
    "title": "Mens Casual Premium Slim Fit T-Shirts ",
    "price": 22.3,
    "description": "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
    "category": "men's clothing",
    "image": "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    "rating": { "rate": 4.1, "count": 259 },
    "color": "white",
    "release": 2022,
    "countInStock": 55
  },
  {
    "id": 3,
    "title": "Mens Cotton Jacket",
    "price": 55.99,
    "description": "great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.",
    "category": "men's clothing",
    "image": "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    "rating": { "rate": 4.7, "count": 500 },
    "color": "brown",
    "release": 2020,
    "countInStock": 15
  },
  {
    "id": 4,
    "title": "Mens Casual Slim Fit",
    "price": 15.99,
    "description": "The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.",
    "category": "men's clothing",
    "image": "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
    "rating": { "rate": 2.1, "count": 430 },
    "color": "blue",
    "release": 2021,
    "countInStock": 19
  },
  {
    "id": 5,
    "title": "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
    "price": 695,
    "description": "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
    "category": "accessories and jewelery",
    "image": "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    "rating": { "rate": 4.6, "count": 400 },
    "color": "selver",
    "release": 2022,
    "countInStock": 7
  },
  {
    "id": 6,
    "title": "Solid Gold Petite Micropave ",
    "price": 168,
    "description": "Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.",
    "category": "accessories and jewelery",
    "image": "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    "rating": { "rate": 3.9, "count": 70 },
    "color": "selver",
    "release": 2020,
    "countInStock": 12
  },
  {
    "id": 7,
    "title": "White Gold Plated Princess",
    "price": 9.99,
    "description": "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day...",
    "category": "accessories and jewelery",
    "image": "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    "rating": { "rate": 3, "count": 400 },
    "color": "selver",
    "release": 2019,
    "countInStock": 2
  },
  {
    "id": 8,
    "title": "Pierced Owl Rose Gold Plated Stainless Steel Double",
    "price": 10.99,
    "description": "Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel",
    "category": "accessories and jewelery",
    "image": "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
    "rating": { "rate": 1.9, "count": 100 },
    "color": "gold",
    "release": 2018,
    "countInStock": 5
  },
  {
    "id": 9,
    "title": "WD 2TB Elements Portable External Hard Drive - USB 3.0",
    "price": 64,
    "description": "USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system",
    "category": "electronics",
    "image": "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
    "rating": { "rate": 3.3, "count": 203 },
    "color": "black",
    "release": 2021,
    "countInStock": 23
  },
  {
    "id": 10,
    "title": "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s",
    "price": 109,
    "description": "Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)",
    "category": "electronics",
    "image": "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    "rating": { "rate": 2.9, "count": 470 },
    "color": "black",
    "release": 2020,
    "countInStock": 7
  },
  {
    "id": 11,
    "title": "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
    "price": 109,
    "description": "3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.",
    "category": "electronics",
    "image": "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
    "rating": { "rate": 4.8, "count": 319 },
    "color": "black",
    "release": 2020,
    "countInStock": 12
  },
  {
    "id": 12,
    "title": "WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive",
    "price": 114,
    "description": "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
    "category": "electronics",
    "image": "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
    "rating": { "rate": 4.8, "count": 400 },
    "color": "black",
    "release": 2022,
    "countInStock": 4
    
  },
  {
    "id": 13,
    "title": "Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin",
    "price": 599,
    "description": "21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz",
    "category": "electronics",
    "image": "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
    "rating": { "rate": 2.9, "count": 250 },
    "color": "black",
    "release": 2021,
    "countInStock": 5
  },
  {
    "id": 14,
    "title": "Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED ",
    "price": 999.99,
    "description": "49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag",
    "category": "electronics",
    "image": "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
    "rating": { "rate": 2.2, "count": 140 },
    "color": "black",
    "release": 2022,
    "countInStock": 9
  },
  {
    "id": 15,
    "title": "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats",
    "price": 56.99,
    "description": "Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates",
    "category": "women's clothing",
    "image": "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
    "rating": { "rate": 2.6, "count": 235 },
    "color": "violet",
    "release": 2020,
    "countInStock": 22
  },
  {
    "id": 16,
    "title": "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
    "price": 29.95,
    "description": "100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON",
    "category": "women's clothing",
    "image": "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
    "rating": { "rate": 2.9, "count": 340 },
    "color": "black",
    "release": 2021,
    "countInStock": 32
  },
  {
    "id": 17,
    "title": "Rain Jacket Women Windbreaker Striped Climbing Raincoats",
    "price": 39.99,
    "description": "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.",
    "category": "women's clothing",
    "image": "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
    "rating": { "rate": 3.8, "count": 679 },
    "color": "blue",
    "release": 2022,
    "countInStock": 16
  },
  {
    "id": 18,
    "title": "MBJ Women's Solid Short Sleeve Boat Neck V ",
    "price": 9.85,
    "description": "95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem",
    "category": "women's clothing",
    "image": "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
    "rating": { "rate": 4.7, "count": 130 },
    "color": "white",
    "release": 2021,
    "countInStock": 44
  },
  {
    "id": 19,
    "title": "Opna Women's Short Sleeve Moisture",
    "price": 7.95,
    "description": "100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort",
    "category": "women's clothing",
    "image": "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg",
    "rating": { "rate": 4.5, "count": 146 },
    "color": "red",
    "release": 2020,
    "countInStock": 31
  },
  {
    "id": 20,
    "title": "DANVOUY Womens T Shirt Casual Cotton Short",
    "price": 12.99,
    "description": "95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.",
    "category": "women's clothing",
    "image": "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
    "rating": { "rate": 3.6, "count": 145 },
    "color": "violet",
    "release": 2022,
    "countInStock": 8
  },
  {
    "id": 21,
    "title": "Baseus 17-in-1 USB C Docking Station to Cast on 3 Monitors",
    "price": 82.32,
    "description": "17-in-1 Docking Station — Up to 16 ports allowing you to connect almost all devices through a single gear; 3*4K HDMI ports to cast different content on each display, also with 100W PD, 2*USB C 3.0, 3*USB A 3.0, 2*USB A 2.0, SD/TF Card reader, 3.5mm Aux, LAN, Triple Extend to the Fullest — Boost productivity by casting up to 3 different contents on displays; Actual pixels up to 4K@30Hz when using a single HDMI port, 1080P@60Hz when using 2 or 3 in Windows system",
    "category": "electronics",
    "image": "https://m.media-amazon.com/images/I/61XsDvwmJpL._AC_SX522_.jpg",
    "rating": { "rate": 3.8, "count": 550 },
    "color": "selver",
    "release": 2021,
    "countInStock": 7
  },
  {
    "id": 22,
    "title": "LapGear Ergo Pro Laptop Stand - Lap Desk with 20 Adjustable Angles, Mouse Pad, and Phone Holder",
    "price": 27.37,
    "description": "Fits Up To 15.6\" Laptops And Most Tablets: 20.5\" X 10.5\" Surface Dimensions Ergonomic: 20 Adjustable Angles For Improved Posture And Screen Viewing Height Design: Wide Surface Includes Integrated Mouse Pad, Stylus Holder, And Phone Slot, Stability: Non-Slip Silicone Strip And Retractable Device Ledge Keep Media Devices In Place",
    "category": "accessories and jewelery",
    "image": "https://m.media-amazon.com/images/I/91jDri1gRYL._AC_SX522_.jpg",
    "rating": { "rate": 4.6, "count": 115 },
    "color": "black",
    "release": 2020,
    "countInStock": 12
  },
  {
    "id": 23,
    "title": "TP-Link Deco Mesh WiFi System (Deco S4) – Up to 5,500 Sq.ft. Works with Alexa",
    "price": 150.88,
    "description": "Faster Wifi Speeds, A Wifi Mesh Network, Up To 100 Devices, A Single Network Name, Strong Wifi Signal, Traditional Wifi Routers",
    "category": "electronics",
    "image": "https://m.media-amazon.com/images/I/614CaSPw+BS._AC_SX522_.jpg",
    "rating": { "rate": 4.6, "count": 223 },
    "color": "white",
    "release": 2021,
    "countInStock": 29
  },
  {
    "id": 24,
    "title": "2020 HP 15.6\" HD LED Display Laptop, Intel Pentium Gold 6405U Processor, 4GB DDR4 RAM, 128GB SSD, HDMI, Webcam, WI-FI",
    "price": 587,
    "description": "15.6\" diagonal, HD (1366 x 768), micro-edge, BrightView, 220 nits, 45% NTSC, Intel Pentium Gold 6405U (2.4 GHz base frequency, 2 MB L3 cache, 2 cores) 128GB SATA M.2 SSD, 4GB DDR4-2400 SDRAM (1 x 4 GB) Optical drive not included, Integrated 10/100/1000 GbE LAN, 1 multi-format SD media card reader Realtek RTL8821CE 802.11a/b/g/n/ac (1x1) Wi-Fi and Bluetooth 4.2 combo, 1 USB 3.1 Gen 1 Type-C (Data Transfer Only, 5 Gb/s signaling rate); 2 USB 3.1 Gen 1 Type-A (Data Transfer Only); 1 RJ-45; 1 AC smart pin; 1 HDMI 1.4b; 1 headphone/microphone combo HP True Vision 720p HD camera with integrated dual array digital microphones, Windows 10 Home in S mode",
    "category": "electronics",
    "image": "https://m.media-amazon.com/images/I/71YNQl3sZRL._AC_SX522_.jpg",
    "rating": { "rate": 4.5, "count": 183 },
    "color": "red",
    "release": 2020,
    "countInStock": 14
  },
  {
    "id": 25,
    "title": "Columbia Men's Glennaker Lake™ Rain Jacket",
    "price": 75,
    "description": "100% Nylon; Imported; Zipper closure; Machine Wash; WATERPROOF TECHNOLOGY: You’ll love our Columbia Men's Glennaker Lake Rain Jacket, it features our Hydroplus waterproof nylon fabric for the ultimate in lightweight, wet weather, protection and comfort. COMPACT AND PACKABLE: A versatile waterproof jacket with an attached hood to ensure complete rain coverage, while its packable design lets you stow it away into its own chest pocket. Perfect for when the last drizzle subsides. HANDY FEATURES: Featuring a convenient stow-away hood, zippered hand pockets, adjustable sleeve cuffs, and a drawcord adjustable hem locks in the dry and keeps out the wet.",
    "category": "men's clothing",
    "image": "https://m.media-amazon.com/images/I/61WBTA1P68S._AC_UX679_.jpg",
    "rating": { "rate": 2.5, "count": 120 },
    "color": "red",
    "release": 2019,
    "countInStock": 11
  },
  {
    "id": 26,
    "title": "Ferrari Portofino 2021",
    "price": 215000,
    "description": "Ferrari has chosen a particularly evocative moniker for this exceptionally versatile drop-top car, referencing one of Italy’s most beautiful towns. Portofino is renowned for its charming tourist port and, over the years, has become internationally synonymous with elegance, sportiness and understated luxury. The launch colour of the new Ferrari has also been dedicated to this marvellous town: Rosso Portofino. A Ferrari designed to be driven every day that also effortlessly converts from an authentic ‘berlinetta’ coupé to a drop-top capable of delivering a unique Ferrari soundtrack and superb driving pleasure even in day-to-day situations.",
    "category": "electronics",
    "image": "https://autoiwc.ru/images/ferrari/ferrari-portofino.webp",
    "rating": { "rate": 5, "count": 32 },
    "color": "red",
    "release": 2021,
    "countInStock": 2
  },
  {
    "id": 27,
    "title": "Star Wars Yoda Dangle Charm",
    "price": 65,
    "description": "Be a true fan with the Star Wars™ Yoda™ Dangle Charm. Hand-finished in sterling silver, this charm includes two dangles, one an openwork design featuring Yoda™ standing with his gimer stick framed by raised ivy, the other a disc featuring hand-applied green and blue enamel with forest details. The backside of the second disc is engraved with \"Do. Or do not. There is no try\" and the bail is engraved with \"Jedi master\".",
    "category": "accessories and jewelery",
    "image": "https://cdn-fsly.yottaa.net/5c17f01f2bb0ac532957f9ee/us.pandora.net/v~4b.1a/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dw11055641/productimages/main/799501C01_RGB.jpg?sw=900&sh=900&sm=fit&sfrm=png&bgcolor=F5F5F5&yocs=A_F_",
    "rating": { "rate": 4.8, "count": 312 },
    "color": "selver",
    "release": 2021,
    "countInStock": 10
  },
  {
    "id": 28,
    "title": "AirPods (3rd generation)",
    "price": 199,
    "description": "Spatial audio with dynamic head tracking places sound all around you. Adaptive EQ automatically tunes music to your ears. All-new contoured design. Force sensor lets you easily control your entertainment, answer or end calls, and more. Sweat and water resistant. Up to 6 hours of listening time with one charge. Up to 30 hours of total listening time with the MagSafe Charging Case. Quick access to Siri by saying “Hey Siri”. Effortless setup, in-ear detection and automatic switching for a magical experience. Easily share audio between two sets of AirPods on your iPhone, iPad, iPod touch or Apple TV",
    "category": "electronics",
    "image": "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MME73_AV2?wid=572&hei=572&fmt=jpeg&qlt=95&.v=1632861338000",
    "rating": { "rate": 4.8, "count": 150 },
    "color": "white",
    "release": 2021,
    "countInStock": 27
  }
]

export default PRODUCT;
